[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.pytest_cache
  | venv
  | virtualenv
  | migrations
  | versions
)/
'''

[tool.isort]
profile = "black"
src_paths = ["isort", "test"]
skip = ["git", "__pycache__", "venv" ,"virtualenv", "migrations", ".tox", ".pytest_cache"]
line_length = 79
atomic = true