"""empty message

Revision ID: 199b46727f51
Revises: 71e1fa40e41e
Create Date: 2021-01-08 17:47:40.444542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "199b46727f51"
down_revision = "71e1fa40e41e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webauthn",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("credentials", sa.String(length=10000), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.did"],),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("webauthn")
    # ### end Alembic commands ###
