"""empty message

Revision ID: c0afbf7317db
Revises: b7821e8be913
Create Date: 2021-01-09 20:43:42.508469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c0afbf7317db"
down_revision = "b7821e8be913"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("webauthn", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("attestation", sa.String(length=20000), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("webauthn", schema=None) as batch_op:
        batch_op.drop_column("attestation")

    # ### end Alembic commands ###
