"""empty message

Revision ID: fcd30ce10201
Revises: c0afbf7317db
Create Date: 2021-01-11 16:34:08.710434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fcd30ce10201"
down_revision = "c0afbf7317db"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("aaguid", sa.LargeBinary(length=16), nullable=True),
        sa.Column("credential_id", sa.LargeBinary(length=64), nullable=True),
        sa.Column(
            "client_data_hash", sa.LargeBinary(length=32), nullable=True
        ),
        sa.Column("public_key", sa.LargeBinary(length=77), nullable=True),
        sa.Column("counter", sa.Integer(), nullable=True),
        sa.Column("attestation", sa.LargeBinary(length=1021), nullable=True),
        sa.Column("info", sa.String(length=1000), nullable=True),
        sa.Column("is_resident", sa.Boolean(), nullable=True),
        sa.Column("last_access", sa.DateTime(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.did"],),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("webauthn", schema=None) as batch_op:
        batch_op.drop_column("credentials")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("webauthn", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("credentials", sa.VARCHAR(length=10000), nullable=True)
        )

    op.drop_table("keys")
    # ### end Alembic commands ###
