name: Deploy

on:
  workflow_run:
    workflows: ["Build and test"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MYSERVERHOST }}
          port: ${{ secrets.MYSERVERPORT }}
          username: ${{ secrets.MYUSERNAME }}
          key: ${{ secrets.MYSSHKEY }}
          script: "cd ${{ secrets.MYPROJECTPATH }} && git pull && ${{ secrets.MYPROJECTPATH }}/venv/bin/pip install -e . && systemctl --user restart onyxcherryauth.service"
