name: Deploy

on:
  workflow_run:
    workflows: ["Build and test"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update code
        uses: appleboy/ssh-action@master
        with:
          host: srv07.mikr.us
          port: 10223
          username: onyxauth
          key: ${{ secrets.MYSSHKEY }}
          script: "cd /home/onyxauth/OnyxcherryOTP && git pull && /home/onyxauth/OnyxcherryOTP/venv/bin/pip install -e . && systemctl --user restart onyxcherryauth.service"
